---
name: CI
on: [push]
env:
  RUST_BACKTRACE: 1
  ARBTEST_BUDGET_MS: 10000
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        # https://drager.github.io/wasm-pack/installer/
      - name: Install wasm-pack
        run: npm install -g wasm-pack
        # https://docs.github.com/en/actions/tutorials/build-and-test-code/nodejs 
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - run: node --version
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1
        id: setup-firefox
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v2
        id: setup-chrome
        with:
          install-chromedriver: true
          install-dependencies: true
      - name: Test
        env:
          FIREFOX_PATH: ${{ steps.setup-firefox.outputs.firefox-path }}
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          # CHROMEDRIVER_PATH: ${{ steps.setup-chrome.outputs.chromedriver-path }}
        run: ./ci/test.sh ${{ matrix.os }}
