---
name: CI
on: [push]
env:
  RUST_BACKTRACE: 1
  ARBTEST_BUDGET_MS: 10000
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        # https://drager.github.io/wasm-pack/installer/
      - name: Install wasm-pack
        run: npm install -g wasm-pack
      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -qqy --no-install-recommends nodejs firefox chromium
          node --version
          firefox --version
          chromium --version
      - name: Test
        run: ./ci/test.sh ${{ matrix.os }}
